import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { getSummary, getAreas, getInsights, getClusters, getComplaints, getWorkforceSummary } from '../services/api';
import { buildAreaIntelligence, getHotspotLevels, getPriorityDistribution, PRIORITY_SCORE_THRESHOLD } from '../services/areaIntelligence';
import { buildMasterProblems, buildObservedRiskAreas, getCityHealth } from '../services/uiIntelligence';
import MapPage from './Map';

const STATUS_ORDER = ['Reported','Under Review','In Progress','Resolved','Assigned'];
function Metric({ label, value, detail, tone='' }) { return <article className={`intel-metric ${tone}`}><div className="metric-label">{label}</div><strong>{value ?? '—'}</strong><span>{detail}</span></article>; }
function BarList({ title, items, tone='cyan' }) { const max = Math.max(...items.map(item => item.count), 1); return <section className="intel-panel"><div className="panel-kicker">SIGNAL DISTRIBUTION</div><h3>{title}</h3><div className="signal-list">{items.map(item => <div className="signal-row" key={item.label}><div><span>{item.label}</span><strong>{item.count}</strong></div><div className="signal-track"><i className={tone} style={{width:`${item.count ? Math.max(4, item.count / max * 100) : 0}%`}}/></div></div>)}</div></section>; }
function Dashboard(){
 const [summary,setSummary]=useState(null),[areas,setAreas]=useState([]),[insights,setInsights]=useState([]),[clusters,setClusters]=useState([]),[complaints,setComplaints]=useState([]),[workforce,setWorkforce]=useState(null),[error,setError]=useState('');
 useEffect(()=>{Promise.all([getSummary(),getAreas(),getInsights(),getClusters(),getComplaints()]).then(([s,a,i,c,rows])=>{setSummary(s);setAreas(a);setInsights(i);setClusters(c);setComplaints(rows)}).catch(()=>setError('City data is temporarily unavailable. Please refresh the command center.'));getWorkforceSummary().then(setWorkforce).catch(()=>setWorkforce(null))},[]);
 const ranked=useMemo(()=>buildAreaIntelligence(areas,complaints),[areas,complaints]); const hotspots=useMemo(()=>getHotspotLevels(clusters),[clusters]); const masters=useMemo(()=>buildMasterProblems(complaints,clusters),[complaints,clusters]); const riskAreas=useMemo(()=>buildObservedRiskAreas(complaints,clusters),[complaints,clusters]); const health=useMemo(()=>getCityHealth(complaints,clusters),[complaints,clusters]);
 const open=complaints.filter(c=>c.status!=='Resolved').length, high=complaints.filter(c=>c.severity==='HIGH').length, priority=complaints.filter(c=>Number(c.priority_score)>=PRIORITY_SCORE_THRESHOLD).length, verification=complaints.filter(c=>c.status==='Resolved').length;
 const statusItems=STATUS_ORDER.map(label=>({label:label==='Assigned'?'Assigned (legacy)':label,count:complaints.filter(c=>c.status===label).length}));
 if(error)return <div className="empty-state panel"><div className="panel-kicker">SYSTEM MESSAGE</div><h2>Command center unavailable</h2><p>{error}</p></div>; if(!summary)return <div className="loading-state"><span className="loading-orbit"/>Syncing city intelligence…</div>;
 return <div className="command-center">
  <div className="command-header"><div><div className="eyebrow"><span className="eyebrow-line"/> CITYLENS / MONITOR</div><h1>City Intelligence Overview</h1><p>AI-powered monitoring of urban problems, risks and priorities.</p></div><div className="system-health"><span className="live-dot"/> SYSTEM ACTIVE <small>DATA-LINKED</small></div></div>
  <div className="workflow-strip"><span className="done">01 REPORT</span><b>→</b><span className="done">02 UNDERSTAND</span><b>→</b><span className="active">03 PRIORITIZE</span><b>→</b><span>04 ACT</span><b>→</b><span>05 VERIFY</span></div>
  <div className="metric-grid"><Metric label="TOTAL REPORTS" value={summary.total_complaints} detail="all complaints in the system"/><Metric label="HIGH SEVERITY" value={high} detail="severity = HIGH" tone="danger"/><Metric label="ACTIVE HOTSPOTS" value={clusters.length} detail={`${hotspots.filter(h=>h.level==='CRITICAL').length} critical concentration`} tone="warning"/><Metric label="PRIORITY SIGNALS" value={priority} detail="stored score ≥ 60" tone="accent"/><Metric label="VERIFICATION PENDING" value={verification} detail="resolved, awaiting response"/></div>
  <div className="hero-grid"><section className="intel-panel health-panel"><div className="panel-kicker">CITYLENS URBAN HEALTH</div><div className="health-row"><div className="health-score">{health.score ?? '—'}<small>/100</small></div><div><h2>{health.label}</h2><p>Composite indicator derived from observed severity, unresolved volume and DBSCAN concentration. Not an official government metric.</p></div></div><div className="health-rail"><span style={{width:`${health.score || 0}%`}}/></div><div className="health-meta"><span>UNRESOLVED <b>{open}</b></span><span>HIGH SEVERITY <b>{high}</b></span><span>HOTSPOTS <b>{clusters.length}</b></span></div></section><section className="intel-panel attention-panel"><div className="panel-kicker">PRIORITIZE / NEXT ACTION</div><h3>What needs attention?</h3>{ranked.slice(0,3).map((area,index)=><Link to="/admin/areas" className="attention-row" key={area.area}><span className="rank">0{index+1}</span><span><strong>{area.area}</strong><small>{area.mainProblem} · {area.total} reports</small></span><b>{Number(area.score||0).toFixed(0)}<small> impact signal</small></b></Link>)}{!ranked.length&&<p className="placeholder">No area data available yet.</p>}</section></div>
  <section className="map-command-panel"><div className="section-heading-command"><div><div className="panel-kicker">MONITOR / LIVE MAP</div><h2>Urban signal map</h2><p>Existing complaints and DBSCAN hotspots across Hyderabad.</p></div><Link className="text-link" to="/admin/map">Open full map →</Link></div><MapPage embedded audience="admin"/></section>
  <div className="intel-columns"><section className="intel-panel"><div className="panel-kicker">UNDERSTAND / FUSION ENGINE</div><h3>Master urban problems</h3><p className="panel-note">Related reports grouped from existing cluster and complaint data. This is a frontend intelligence view, not duplicate detection.</p>{masters.slice(0,3).map(master=><div className="master-card" key={master.id}><div className="master-id">{master.id}<span className={`badge ${master.status}`}>{master.status}</span></div><strong>{master.title}</strong><span>{master.area} · {master.reports} related reports · {master.issueTypes} issue types</span><div className="master-flow"><i>{master.reports} reports</i><b>→</b><em>MASTER PROBLEM</em><b>→</b><i>{master.avgPriority ?? '—'} priority</i></div></div>)}{!masters.length&&<p className="placeholder">No multi-report groupings detected.</p>}</section><section className="intel-panel"><div className="panel-kicker">MONITOR / OBSERVED PATTERNS</div><h3>Rising-risk areas</h3><p className="panel-note">Observed from recent activity and existing hotspots. This is not future prediction.</p>{riskAreas.slice(0,4).map(area=><div className="risk-row" key={area.area}><span className={`risk-dot ${area.level.toLowerCase()}`}/><div><strong>{area.area}</strong><small>{area.recent} recent reports · {area.hotspots} hotspots · {area.unresolved} unresolved</small></div><b>{area.level === 'RISING-RISK' ? `+${Math.max(area.trend,0)}` : area.level}</b></div>)}</section></div>
  <div className="overview-bottom"><BarList title="Workflow status" items={statusItems}/><section className="intel-panel insights-panel"><div className="panel-kicker">ANALYZE / AI INSIGHTS</div><h3>Current situation</h3>{insights.slice(0,4).map((insight,index)=><div className="insight-line" key={index}><span>0{index+1}</span><p>{insight}</p></div>)}{!insights.length&&<p className="placeholder">No insights available.</p>}</section>{workforce&&<section className="intel-panel"><div className="panel-kicker">FIELD OPERATIONS</div><h3>Authority response capacity</h3><div className="response-stat"><strong>{workforce.active ?? 0}</strong><span>active assignments</span></div><div className="response-grid"><span>Completed <b>{workforce.completed ?? 0}</b></span><span>Overdue <b>{workforce.overdue ?? 0}</b></span></div><Link className="btn secondary" to="/admin/workforce">Open workforce →</Link></section>}</div>
 </div>;
}
export default Dashboard;
